language: node_js
node_js:
  - "node"
script:
  - npm install
before_deploy: 
  - npm run generate
  - ls
deploy:
  provider: firebase
  token:
    secure: "BHZJkuxrRvJRVm4VUHZkOO7fv0epapbZgNJU37Vj2/juLKLNvTNGP6lZ0ufHBls4fPJOQjozxAtju5zjNVjsu3gsWIIOVCyxuFj6LZOImsoZRCIFXi/rKQDIhWBdRUtvAAPGg79iS4Wipr450kHbeZ8wKAKKeDIUHFS3jbC7uA6sB92Fx0SjCwVXiz7kr+KbbETA8YQWzissEG3CrJR8kblw0rNGHpN/NUr/l52+JwcXsvAo6P/kux0GMuvnJq4ijinvvzA/OxsJ6CsRd1/w82ZUurW0By/tpw3LUgCoJQ2vOKvoBpLWyHWV8HKm+xNHlXaDzTO2VtbkoP6dtDD4ks50xJlX9cX8a6/bFWZvst4AqSBDSefABO4oY30kdP5AbdL2RRBLDXbeb7glBvo8Kv0af99gJD4oy07cJYfC/qQGS8ZYxpoH3gdebtNLsvEuf+r1APgKsAsIL8q4lt9+cNcuY1Bz6PAdqAoZFZuWERa99zG37lssRZ4nBj6T7+uquRGysBD961DnJ2c4PSieo9uWSbFnoHnNGVHU+igjd6qcVpZJD0u2oHw6RytG1Lf/w0lx2WuSk881P+klsnJKunwPIm5J8qz7vn0+cc79OYnSMc5LqLFqS1PQN5pJ4WJu1rAB3csa8Hlor4z5EcuEUoDfnA1iURVsDW1pJszK8RU="